from __future__ import annotations

import hashlib
import json
import tempfile
import unittest
from pathlib import Path

import numpy as np
from PIL import Image

from reference_utils import FixtureError, flatten_tensor_outputs, summarize_array, validate_fixture


def make_fixture(tmp_path: Path) -> Path:
    images = []
    fixture_dir = tmp_path / "fixture"
    image_dir = fixture_dir / "images"
    image_dir.mkdir(parents=True)
    for order, color in enumerate(((255, 0, 0), (0, 255, 0))):
        image_path = image_dir / f"view-{order:02}.png"
        Image.new("RGB", (16, 12), color).save(image_path)
        payload = image_path.read_bytes()
        images.append(
            {
                "order": order,
                "path": f"images/{image_path.name}",
                "sha256": hashlib.sha256(payload).hexdigest(),
                "width": 16,
                "height": 12,
                "bytes": len(payload),
                "description": f"view {order}",
            }
        )
    manifest = {
        "schema_version": 1,
        "scene_id": "unit-test",
        "description": "generated test fixture",
        "provenance": {
            "source": "generated by test",
            "license": "test-only",
            "permission_record": "this test",
            "contains_sensitive_content": False,
            "approved_for_public_repository": False,
        },
        "images": images,
    }
    manifest_path = fixture_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest), encoding="utf-8")
    return manifest_path


class ReferenceUtilsTest(unittest.TestCase):
    def test_valid_fixture_passes(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            manifest, paths = validate_fixture(make_fixture(Path(directory)))
            self.assertEqual(manifest["scene_id"], "unit-test")
            self.assertEqual(len(paths), 2)

    def test_hash_drift_fails(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            manifest_path = make_fixture(Path(directory))
            image_path = manifest_path.parent / "images/view-00.png"
            image_path.write_bytes(image_path.read_bytes() + b"drift")
            with self.assertRaisesRegex(FixtureError, "sha256 mismatch"):
                validate_fixture(manifest_path)

    def test_wrong_order_fails(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            manifest_path = make_fixture(Path(directory))
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            manifest["images"][0]["order"] = 1
            manifest_path.write_text(json.dumps(manifest), encoding="utf-8")
            with self.assertRaisesRegex(FixtureError, "image order"):
                validate_fixture(manifest_path)

    def test_summary_detects_non_finite_and_is_stable(self) -> None:
        array = np.array([[1.0, np.nan], [np.inf, -2.0]], dtype=np.float32)
        first = summarize_array(array)
        second = summarize_array(array.copy())
        self.assertEqual(first["sha256"], second["sha256"])
        self.assertEqual(first["finite"], 2)
        self.assertEqual(first["non_finite"], 2)
        self.assertEqual(first["min"], -2.0)
        self.assertEqual(first["max"], 1.0)

    def test_flatten_outputs_has_stable_names(self) -> None:
        nested = {"z": [np.zeros(1)], "a": np.ones(2)}
        self.assertEqual(
            [name for name, _ in flatten_tensor_outputs(nested)], ["a", "z[0]"]
        )

    def test_summary_empty_array(self) -> None:
        summary = summarize_array(np.array([], dtype=np.float32))
        self.assertEqual(summary["elements"], 0)
        self.assertEqual(summary["finite"], 0)
        self.assertIsNone(summary["mean"])


if __name__ == "__main__":
    unittest.main()
